# Generated by Django 4.2.2 on 2023-06-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('title', models.CharField(max_length=250, verbose_name='Название статьи')),
                ('text', models.TextField(max_length=250, verbose_name='Статья')),
                ('data', models.DateTimeField(verbose_name='Дата создания')),
            ],
        ),
    ]
