# Generated by Django 4.2.2 on 2023-07-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_articles_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(default='null', upload_to='LW/news/static/news/img/', verbose_name='Изображение'),
        ),
    ]
