# Generated by Django 4.2.2 on 2023-07-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_articles_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(default='null', upload_to='media/', verbose_name='Изображение'),
        ),
    ]
