# Generated by Django 4.2.2 on 2023-07-05 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(default='null', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
